export const KEYWORDS: Record<string, string> = Object.freeze({
    "Poder de Habilidade": "icon_ap",
    "Armadura": "icon_armor",
    "Penetração de Armadura": "icon_armor_pen",
    "Dano de Ataque": "icon_ad",
    "Velocidade de Ataque": "icon_as",
    "Velocidade de Movimento": "icon_ms",
    "Redução de Recarga": "icon_cdr",
    "Chance de Acerto Crítico": "icon_crit_chance",
    "Dano de Acerto Crítico": "icon_crit_damage",
    "Poder de Cura e Escudo": "icon_heal_shield",
    "Vida": "icon_health",
    "Regeneração de Vida": "icon_health_regen",
    "Roubo de Vida": "icon_life_steal",
    "Penetração Mágica": "icon_magic_pen",
    "Resistência Mágica": "icon_mr",
    "Mana": "icon_mana",
    "Regeneração de Mana": "icon_mana_regen",
    "Onivampirismo": "icon_omnivamp",
    "Vampirismo Físico": "icon_physical_vamp",
    "Aceleração de Habilidade": "icon_haste",
    "Tenacidade": "icon_tenacity",
    "Dano Verdadeiro": "icon_true_damage"
});